version: "3.9"
x-logging:
  &x-logging
  options:
    max-size: 50m
    max-file: "1"
  driver: json-file
x-restart: &x-restart "unless-stopped"
x-stop-grace-period: &x-stop-grace-period "3s"

services:
  testabc:
    image: test:test #307657941387.dkr.ecr.us-east-1.amazonaws.com/windrose:humble-source-sim
    privileged: true
    container_name: test
    environment:
      #      - CYCLONEDDS_URI=<CycloneDDS><Domain><General><NetworkInterfaceAddress>docker0</></></></>
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - DISPLAY=unix$DISPLAY
      - XAUTHORITY=$XAUTHORITY
    volumes:
      #- /home/david/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - ${PWD}:/home/usr
    network_mode: "host"
    logging: *x-logging
    restart: *x-restart
    stop_grace_period: *x-stop-grace-period
    command: tail -F anything
    working_dir: /usr/home